# ----
# Site

title: Rette deine Lieblingssendung!
url: https://clean-oryx.cloudvent.net
baseurl:
google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Verein für die Rettung meiner Lieblingssendung
# author:
#   name:
#   email:
#   twitter: # twitter username without the @ symbol
social:
  name: Verein für die Rettung meiner Lieblingssendung
  links:
    - http://twitter.com/lieblingssendung

# -----
# Build

collections:
  staff_members:
    _hide_content: false
    _options:
      image:
        width: 250
        height: 250

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
  -
    scope:
      path: ""
    values:
      layout: "default"

donation_embed: '<script src="https://donorbox.org/widget.js" type="text/javascript"></script><iframe src="https://donorbox.org/embed/cc502905-0b4b-4c97-83ee-01a5da297747" height="685px" width="100%" style="max-width:500px; min-width:310px; max-height:none!important" seamless="seamless" name="donorbox" frameborder="0" scrolling="no"></iframe>'
newsletter_action: "//meinelieblingssendung.us17.list-manage.com/subscribe/post?u=f73f0d530951cfdb82ddd191d&amp;id=0db7fe5366"

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - package-lock.json
  - _config.yml
  - .gitignore

_options:
  header_background_image:
    width: 1880
    height: 1880
  newsletter_background_image:
    width: 1880
    height: 1880
